In [4]:
import numpy as np

In [2]:
np.__version__

'2.4.6'

In [10]:
# Array can store only one data type 

In [ ]:
# boolean -> int -> float -> string

In [21]:
arr = np.array([True, True,False])
print(arr)

[ True  True False]


In [22]:
arr = np.array([True, True,False,0])
print(arr)

[1 1 0 0]


In [23]:
arr = np.array([True, True,False,1, 3.14,])
print(arr)

[1.   1.   0.   1.   3.14]


In [16]:
arr1 = np.array([1,2,3,4, True,22.4])
print(arr1)

[ 1.   2.   3.   4.   1.  22.4]


In [19]:
arr1 = np.array([True, 3.14, "a"])
print(arr1)

['True' '3.14' 'a']


In [ ]:
# List can store multiple data types 

In [18]:
arr2 = list([True, 3.14, "a"])
print(arr2)

[True, 3.14, 'a']


In [4]:
np.array(list[1,2,3])

array(list[1, 2, 3], dtype=object)

In [ ]:
# d/w range and arange

In [5]:
range(1,6)

range(1, 6)

In [6]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [7]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
np.array([1,11])

array([ 1, 11])

In [24]:
# one dimensional array

In [5]:
list1 = np.array([1,2,3,4])

In [27]:
type(list1)

numpy.ndarray

In [29]:
list1.ndim

1

In [6]:
list1.shape

(4,)

In [7]:
list1.size

4

In [16]:
A = np.array([
    [1,-1,3],
    [2,5,1],
    [6,2,1]
])

print(A.ndim)
print(A.shape)
print(A.size)

2
(3, 3)
9


In [17]:
# 2*(2*2)

In [18]:
B = np.array([
    [[1,2,3],
    [4,5,6]],
    
    [[7,8,9],
    [10,11,12]],

    [[13,14,15],
    [16,17,18]]
])

print(B.ndim)
print(B.shape)
print(B.size)

3
(3, 2, 3)
18


In [24]:
zeros = np.zeros(3, dtype= "int")
zeros

array([0, 0, 0])

In [27]:
zeros = np.zeros((3,3), dtype= "int")
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
zeros = np.zeros((2,3,3), dtype= "int")
zeros

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [31]:
ones = np.ones((2,3,3), dtype= "int")
ones

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [37]:
dig = np.eye(3,3, dtype= "int")
dig

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
dig = np.eye(3, dtype= "int")
dig

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
linespace = np.linspace(0,10,5, dtype="int")
linespace

array([ 0,  2,  5,  7, 10])