In [2]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr[1:4]

array([2, 3, 4])

In [5]:
arrlist = list(([1,2,3,4,5]))

In [6]:
arrlist[1:4]

[2, 3, 4]

In [12]:
arr[::]

array([1, 2, 3, 4, 5])

In [13]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [14]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
arr2d[0::2,0::1]

array([[1, 2, 3],
       [7, 8, 9]])

In [4]:
#need
# 7,8,9
# 12,13,14
# 17,18,19

In [3]:
arr = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

In [5]:
arr[1:-1:1,1:-1:1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [6]:
list1 = list([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [8]:
list1[0]

[1, 2, 3]

In [7]:
list1[-1]

[7, 8, 9]

In [9]:
list2 = [[1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11, 12]]
list2

[[1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11, 12]]

In [10]:
list2[0]

[1, 2, 3]

In [16]:
list2[1]

[4, 5, 6, 7]

In [18]:
# flatten 

list2.flatten()

AttributeError: 'list' object has no attribute 'flatten'

In [4]:
list2 = [[1,2,3], [4,5,6,7], [8,9,10,11,12]]
list2

[[1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11, 12]]

In [5]:
res = []
for i in list2:
    temp = i
    for element in temp:
        res.append(element)

res

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [25]:
np.array(list2).flatten()

array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14, 16, 17, 18, 19])

In [6]:
row1 = [1,2,3]
row2 = [4,5,6]

row1 + row2

[1, 2, 3, 4, 5, 6]

In [8]:
np.array(row1) + np.array(row2)

array([5, 7, 9])

In [9]:
np.array(row1) * np.array(row2)

array([ 4, 10, 18])

In [10]:
np.array(row1) / np.array(row2)

array([0.25, 0.4 , 0.5 ])

In [11]:
np.array(row1) % np.array(row2)

array([1, 2, 3])

In [13]:
arr = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

flatten_arr = arr.flatten()
flatten_arr[1] = 100

print(flatten_arr)
print(arr)

[  1 100   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
arr = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

ravel_arr = arr.ravel()
ravel_arr[1] = 100

print(ravel_arr)
print(arr)

[  1 100   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25]
[[  1 100   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


In [18]:
row1 = [1,2,3]
row2 = [4,5,6]


np.vstack((row1,row2))


array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.hstack((row1,row2))

array([1, 2, 3, 4, 5, 6])

In [31]:
arr = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

np.split(arr, 4)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]])]